### PR TITLE
Fix search on User Rankings and Add Ratings page

### LINKED ISSUE #114: [BUG] Search on User Rankings page not working
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

production

### Description

On the user ratings page, the search does not work.
In the browser console you can see an error:
`Uncaught TypeError: t is not a function`

### Steps to Reproduce

1. Go to user rankings page.
2. Search anything in the search bar on the top.
3. Users are not filtered.
4. Browser console has an error: `Uncaught TypeError: t is not a function`

### Screenshots

_No response_

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

In `app/rankings/page.js`, we aren't passing setKeyword callback to <SideNav> like we do in `app/page.js`. Need to pass this callback and filter the `Users` component with keyword by searching on name of the users

### PR DESCRIPTION
**Pull request by vneogi199**
## Fixes Issue #114 

Closes #114 
## Changes proposed

- Create `fulltext` index on `ratings` collection on `username` (needs to be done on appwrite in production)
- Add `react-use` library to perform debouncing on search query (currently the search is done for every keypress, changed it to search only after 200ms)
- On `User Rankings` page, perform search using `searchParams`
- On `Add Ratings` page, hide search bar

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots
Default User Rankings page
image

User Rankings page after search query `vin`
image

Add Ratings page (search box hidden)
image

## Note to reviewers

This PR needs change to Appwrite schema as an index is added to `username` attribute in `ratings` collection.

## Summary by CodeRabbit

- **New Features**
	- Enhanced search functionality across the app, including keyword-based filtering for user ratings.
	- Introduced a more dynamic querying system for improved user interaction.
- **Documentation**
	- Updated README to include new steps for database indexing.
- **Refactor**
	- Improved search performance and user experience through debouncing input in the navigation bar.
	- Adjusted the visibility of the search feature in different components for a more intuitive user interface.

### CODE REVIEW

File: src/components/SideNav.js [hunk 1]
```diff
@@ -55,6 +63,23 @@ export default function SideNav({ setKeyword, children }) {
...
+    [searchKeyword],
+  );
+
+  useEffect(() => {
+    if (!debouncedSearchKeyword) {
+      router.push(pathName);
+    } else {
+      router.push(`?keyword=${debouncedSearchKeyword}`);
+    }
+  }, [debouncedSearchKeyword, router, pathName]);
```
Comment (Vijaykv5) [inline src/components/SideNav.js:81]: Is `pathName` really needed in dependency array elements

Comment (vneogi199) [reply src/components/SideNav.js:81]: it is used at line 77, though I don't see any impact keeping/removing it from the dependency array

**Review by eddiejaoude — APPROVED** [review]
Thank you 👍
