### PR TITLE
fix: unauthenticated Access to /rate URL

### LINKED ISSUE #46: [BUG] Unauthenticated Access to /rate URL
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

production

### Description

I have discovered a bug in the application where the /rate URL is accessible without requiring user authentication. It is crucial to implement proper authentication checks for the /rate route to ensure that only authenticated users can access it. 

### Steps to Reproduce

1. hit this url https://repo-rater.eddiehub.io/rate in the browser without login and you can able to access the rate page.

### Screenshots

_No response_

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

_No response_

### PR DESCRIPTION
**Pull request by Nithishvb**
closes #46

This PR addresses a security vulnerability where the /rate URL was accessible without requiring user authentication. The issue allowed unauthorized users to access /rate page.

### CODE REVIEW

**Comment by eddiejaoude** [comment]
Thank you 👍  I will test after lunch

File: src/app/rate/page.js [hunk 1]
```diff
@@ -1,6 +1,25 @@
...
+import { account } from "@/config/appwrite-client";
 
 export default function Rate() {
+  const router = useRouter();
+
+  const getUser = async () => {
+    try {
+      const user = await account.getSession("current");
+    } catch (e) {
+      router.push('/auth/login');
```
Comment (eddiejaoude) [inline src/app/rate/page.js:15]: Update quotes to be consistent with project

```suggestion
      router.push("/auth/login");
```

**Review by eddiejaoude — APPROVED** [review]
Thank you 👍
